#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

develop_change=$(git diff --cached --exit-code ./docs/todos.org \
                     > /dev/null; echo $?)

# update develop.md given conditions
if [ -f ./docs/todos.org ] && [ "$develop_change" -eq "1" ]; then
  # convert todos.org to todos.md
  pandoc -f org -t markdown -o ./docs/todos.md ./docs/todos.org
  # replace TODOs cleanly
  sed -i 's/\[TODO\]{.*}/**TODO**/g' ./docs/todos.md
  sed -i 's/\[DONE\]{.*}/**DONE**/g' ./docs/todos.md
  # add requirements.txt to stage for commit
  git add ./docs/todos.md
fi
